[package]
name = "todos"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced_core.workspace = true
# iced.features = ["async-std", "debug", "winit", "a11y", "tiny-skia"]
# TODO(POP): Fix a11y not working with new winit
iced.features = ["async-std", "debug", "winit", "tiny-skia"]

once_cell.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "fast-rng", "serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std.workspace = true
directories-next = "2.0"
tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced.workspace = true
iced.features = ["debug", "webgl"]

uuid = { version = "1.0", features = ["js"] }
web-sys = { workspace = true, features = ["Window", "Storage"] }
wasm-timer.workspace = true

[package.metadata.deb]
assets = [
    [
        "target/release-opt/todos",
        "usr/bin/iced-todos",
        "755",
    ],
    [
        "iced-todos.desktop",
        "usr/share/applications/",
        "644",
    ],
]
