[package]
name = "iced_widget"
description = "The built-in widgets for iced"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[features]
lazy = ["ouroboros"]
image = ["iced_renderer/image"]
svg = ["iced_renderer/svg"]
canvas = ["iced_renderer/geometry"]
qr_code = ["canvas", "qrcode"]
wgpu = ["iced_renderer/wgpu"]
advanced = []
a11y = ["iced_accessibility"]
wayland = ["sctk"]

[dependencies]
iced_renderer.workspace = true
iced_runtime.workspace = true
iced_accessibility.workspace = true
iced_accessibility.optional = true
sctk.workspace = true
sctk.optional = true
num-traits.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
window_clipboard.workspace = true
dnd.workspace = true

ouroboros.workspace = true
ouroboros.optional = true

qrcode.workspace = true
qrcode.optional = true
