[package]
name = "scrollable"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["debug", "winit"]
iced_core.workspace = true
once_cell.workspace = true
